name: upload_file
on: 
    push:
        branches:
            main
    
    pull_request:
        types: 
            - opened
jobs:
    upload:
        runs-on: ubuntu-latest
        outputs:
          message: ${{steps.upload.outputs.msg}}
        steps:
            - name: download file
              uses: actions/checkout@v4
            - name: install node  
              uses: actions/setup-node@v3
              with: 
                node-version: 18

            - name: install dependencies
              run: npm install
            - name: upload file
              id: upload
              run: echo "msg=myapp" >> $GITHUB_OUTPUT
    
    deploy:
        needs: upload
        runs-on: ubuntu-latest

        steps: 
            - name: use_output
              run: echo "Message from upload job ${{needs.upload.outputs.message}}"
    
    docker:
        needs: [upload ,deploy]
        runs-on: ubuntu-latest
         
        steps:
           - name: download code
             uses: actions/checkout@v4
           - name: docker compose
             run: docker compose up -d --build
           - name: check container
             run: docker ps
           - name: test app
             run: curl http://localhost:8080